SET SERVEROUTPUT ON;
SET FEEDBACK OFF;

DECLARE
        configuration_id CONFIGURATION.CONFIGURATIONID%TYPE;
        container_id CONTAINER.CONTAINERID%TYPE;

BEGIN
        SELECT CONFIGURATION.CONFIGURATIONID INTO configuration_id FROM CONFIGURATION WHERE CONFIGURATION.CONFIGURATIONNAME = 'CURRENT.AOS';
        SELECT CONTAINER.CONTAINERID INTO container_id FROM CONTAINER WHERE CONTAINER.PATH = 'CONTROL/LMC2' AND CONTAINER.CONTAINERNAME = 'cppContainer' AND CONTAINER.CONFIGURATIONID = configuration_id;
        FOR component_row in (SELECT * FROM COMPONENT WHERE COMPONENT.CONTAINERID = container_id ORDER BY COMPONENT.PATH, COMPONENT.COMPONENTNAME  )
        LOOP
            dbms_output.put_line(component_row.PATH|| '/' ||component_row.COMPONENTNAME);
        END LOOP;
END;
/
EXIT;
